name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@23.23.52.7 "
        cd iweb-app/backend/iwebro_backend &&
        git reset --hard HEAD &&   # Reset all tracked files to their last commit
        git clean -fd &&           # Remove untracked files and directories
        git pull origin main &&
        npm install &&
        pm2 restart all"
